### ISSUE TITLE
Don't upload files during class definition

### ISSUE THREAD

**Issue by cpennington** [DongwookYoon/RichReviewXBlock#2]
Re: https://github.com/DongwookYoon/RichReviewXBlock/blob/master/richreview/richreview.py#L37-L75

It's not a good idea to be uploading static assets during class declaration like that. That declaration happens at times you can't (as an xblock author) predict, and as a system administrator, you don't want to have file uploads happen just because you happened to import the richreview python file.

The intention behind https://github.com/edx/XBlock/blob/master/xblock/runtime.py#L483-L500 in XBlock is to allow an XBlock author to have a standard way to get a url to their own files, while allowing the XBlock platform maintainer to put those files in a sensible place. So, right now (for instance), we serve those files via the LMS, but in the future, we could upload them to a CDN at install time, and then just have the application reference them as needed.

**Comment by DongwookYoon** [comment]
Now it serves the webapp files per request:
https://github.com/DongwookYoon/RichReviewXBlock/blob/master/richreview/richreview.py#L152-L165
Could you please check?
