### ISSUE TITLE
Race Conditions (and too much data) in the Group Fields

### ISSUE THREAD

**Issue by cpennington** [DongwookYoon/RichReviewXBlock#3]
I think you're already aware of this (based on what we were talking about this afternoon), but https://github.com/DongwookYoon/RichReviewXBlock/blob/master/richreview/richreview.py#L190-L209 won't scale as the number of students grows (the XBlock infrastructure will put all of the group assignments in a single dictionary in memory).

**Comment by DongwookYoon** [comment]
You are right. That's why I wrapped them in the two functions so that they can be substituted by the runtime solution that we've discussed.
